image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
  - ms-azuretools.vscode-docker
tasks:
  - name: Set Kubernetes context
    command: echo $K8S_CTX | base64 -d > ~/.kube/config
  - name: Set DigitalOcean API token
    command: doctl auth init -t $DO_TOKEN
