apiVersion: v1
kind: Pod
metadata:
  name: hungry-busybox
spec:
  containers:
  - name: hungry-busybox-container
    image: busybox
    command: ["dd", "if=/dev/zero", "of=/dev/null"]
    resources:
      requests:
        # NOTE: Increse CPU request.
        cpu: 700m
        memory: 5Mi